[package]
name = "my_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }   # Required for parsing Rust code
quote = "1.0" # Required for generating Rust code
proc-macro2 = "1.0"